
// Objective-C API for talking to the following Go packages
//
//	github.com/zecrey-labs/zecrey-crypto/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Zecrey_FRAMEWORK_H__
#define __Zecrey_FRAMEWORK_H__

#include "Zecrey.objc.h"
#include "Universe.objc.h"

#endif
