
// Objective-C API for talking to the following Go packages
//
//	github.com/zecrey-labs/zecrey-crypto/mobile/zecrey-legend
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Zecrey_legend_FRAMEWORK_H__
#define __Zecrey_legend_FRAMEWORK_H__

#include "Zecrey_legend.objc.h"
#include "Universe.objc.h"

#endif
